/*
 * PapSign API
 * The PapSign API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@papsign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.GroupIdentities;
import io.swagger.client.model.GroupPermission;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * AccessibleIdentities
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-27T15:04:00.483Z[GMT]")
public class AccessibleIdentities {
  @SerializedName("list")
  private List<GroupIdentities> list = new ArrayList<GroupIdentities>();

  @SerializedName("permission")
  private GroupPermission permission = null;

  public AccessibleIdentities list(List<GroupIdentities> list) {
    this.list = list;
    return this;
  }

  public AccessibleIdentities addListItem(GroupIdentities listItem) {
    this.list.add(listItem);
    return this;
  }

   /**
   * Get list
   * @return list
  **/
  @Schema(required = true, description = "")
  public List<GroupIdentities> getList() {
    return list;
  }

  public void setList(List<GroupIdentities> list) {
    this.list = list;
  }

  public AccessibleIdentities permission(GroupPermission permission) {
    this.permission = permission;
    return this;
  }

   /**
   * Get permission
   * @return permission
  **/
  @Schema(required = true, description = "")
  public GroupPermission getPermission() {
    return permission;
  }

  public void setPermission(GroupPermission permission) {
    this.permission = permission;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessibleIdentities accessibleIdentities = (AccessibleIdentities) o;
    return Objects.equals(this.list, accessibleIdentities.list) &&
        Objects.equals(this.permission, accessibleIdentities.permission);
  }

  @Override
  public int hashCode() {
    return Objects.hash(list, permission);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessibleIdentities {\n");
    
    sb.append("    list: ").append(toIndentedString(list)).append("\n");
    sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
