/*
 * PapSign API
 * The PapSign API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@papsign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.DecodedPageDTO;
import io.swagger.client.model.SignedPDFInfoDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * DecodedDocumentDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-27T15:04:00.483Z[GMT]")
public class DecodedDocumentDTO {
  @SerializedName("pdf")
  private SignedPDFInfoDTO pdf = null;

  @SerializedName("standard")
  private List<DecodedPageDTO> standard = new ArrayList<DecodedPageDTO>();

  public DecodedDocumentDTO pdf(SignedPDFInfoDTO pdf) {
    this.pdf = pdf;
    return this;
  }

   /**
   * Get pdf
   * @return pdf
  **/
  @Schema(description = "")
  public SignedPDFInfoDTO getPdf() {
    return pdf;
  }

  public void setPdf(SignedPDFInfoDTO pdf) {
    this.pdf = pdf;
  }

  public DecodedDocumentDTO standard(List<DecodedPageDTO> standard) {
    this.standard = standard;
    return this;
  }

  public DecodedDocumentDTO addStandardItem(DecodedPageDTO standardItem) {
    this.standard.add(standardItem);
    return this;
  }

   /**
   * Get standard
   * @return standard
  **/
  @Schema(required = true, description = "")
  public List<DecodedPageDTO> getStandard() {
    return standard;
  }

  public void setStandard(List<DecodedPageDTO> standard) {
    this.standard = standard;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DecodedDocumentDTO decodedDocumentDTO = (DecodedDocumentDTO) o;
    return Objects.equals(this.pdf, decodedDocumentDTO.pdf) &&
        Objects.equals(this.standard, decodedDocumentDTO.standard);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pdf, standard);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DecodedDocumentDTO {\n");
    
    sb.append("    pdf: ").append(toIndentedString(pdf)).append("\n");
    sb.append("    standard: ").append(toIndentedString(standard)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
