/*
 * PapSign API
 * The PapSign API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@papsign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.CountryCode;
import io.swagger.client.model.Type;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * IdentityInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-27T15:04:00.483Z[GMT]")
public class IdentityInfo {
  @SerializedName("address")
  private String address = null;

  @SerializedName("companyID")
  private String companyID = null;

  @SerializedName("companyName")
  private String companyName = null;

  @SerializedName("companyType")
  private String companyType = null;

  @SerializedName("country")
  private CountryCode country = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("personalID")
  private String personalID = null;

  @SerializedName("personalName")
  private String personalName = null;

  @SerializedName("type")
  private Type type = null;

  @SerializedName("uid")
  private Integer uid = null;

  public IdentityInfo address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(description = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public IdentityInfo companyID(String companyID) {
    this.companyID = companyID;
    return this;
  }

   /**
   * Get companyID
   * @return companyID
  **/
  @Schema(description = "")
  public String getCompanyID() {
    return companyID;
  }

  public void setCompanyID(String companyID) {
    this.companyID = companyID;
  }

  public IdentityInfo companyName(String companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * Get companyName
   * @return companyName
  **/
  @Schema(description = "")
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }

  public IdentityInfo companyType(String companyType) {
    this.companyType = companyType;
    return this;
  }

   /**
   * Get companyType
   * @return companyType
  **/
  @Schema(description = "")
  public String getCompanyType() {
    return companyType;
  }

  public void setCompanyType(String companyType) {
    this.companyType = companyType;
  }

  public IdentityInfo country(CountryCode country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @Schema(description = "")
  public CountryCode getCountry() {
    return country;
  }

  public void setCountry(CountryCode country) {
    this.country = country;
  }

  public IdentityInfo email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @Schema(description = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public IdentityInfo personalID(String personalID) {
    this.personalID = personalID;
    return this;
  }

   /**
   * Get personalID
   * @return personalID
  **/
  @Schema(description = "")
  public String getPersonalID() {
    return personalID;
  }

  public void setPersonalID(String personalID) {
    this.personalID = personalID;
  }

  public IdentityInfo personalName(String personalName) {
    this.personalName = personalName;
    return this;
  }

   /**
   * Get personalName
   * @return personalName
  **/
  @Schema(description = "")
  public String getPersonalName() {
    return personalName;
  }

  public void setPersonalName(String personalName) {
    this.personalName = personalName;
  }

  public IdentityInfo type(Type type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(required = true, description = "")
  public Type getType() {
    return type;
  }

  public void setType(Type type) {
    this.type = type;
  }

  public IdentityInfo uid(Integer uid) {
    this.uid = uid;
    return this;
  }

   /**
   * Get uid
   * @return uid
  **/
  @Schema(required = true, description = "")
  public Integer getUid() {
    return uid;
  }

  public void setUid(Integer uid) {
    this.uid = uid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdentityInfo identityInfo = (IdentityInfo) o;
    return Objects.equals(this.address, identityInfo.address) &&
        Objects.equals(this.companyID, identityInfo.companyID) &&
        Objects.equals(this.companyName, identityInfo.companyName) &&
        Objects.equals(this.companyType, identityInfo.companyType) &&
        Objects.equals(this.country, identityInfo.country) &&
        Objects.equals(this.email, identityInfo.email) &&
        Objects.equals(this.personalID, identityInfo.personalID) &&
        Objects.equals(this.personalName, identityInfo.personalName) &&
        Objects.equals(this.type, identityInfo.type) &&
        Objects.equals(this.uid, identityInfo.uid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, companyID, companyName, companyType, country, email, personalID, personalName, type, uid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdentityInfo {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    companyID: ").append(toIndentedString(companyID)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    companyType: ").append(toIndentedString(companyType)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    personalID: ").append(toIndentedString(personalID)).append("\n");
    sb.append("    personalName: ").append(toIndentedString(personalName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
