/*
 * PapSign API
 * The PapSign API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@papsign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PDFSignatureProcessSignDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-27T15:04:00.483Z[GMT]")
public class PDFSignatureProcessSignDTO {
  @SerializedName("identityID")
  private Long identityID = null;

  @SerializedName("processID")
  private Long processID = null;

  public PDFSignatureProcessSignDTO identityID(Long identityID) {
    this.identityID = identityID;
    return this;
  }

   /**
   * Get identityID
   * minimum: 9223372036854775616
   * maximum: -9223372036854775616
   * @return identityID
  **/
  @Schema(required = true, description = "")
  public Long getIdentityID() {
    return identityID;
  }

  public void setIdentityID(Long identityID) {
    this.identityID = identityID;
  }

  public PDFSignatureProcessSignDTO processID(Long processID) {
    this.processID = processID;
    return this;
  }

   /**
   * Get processID
   * minimum: 9223372036854775616
   * maximum: -9223372036854775616
   * @return processID
  **/
  @Schema(required = true, description = "")
  public Long getProcessID() {
    return processID;
  }

  public void setProcessID(Long processID) {
    this.processID = processID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PDFSignatureProcessSignDTO pdFSignatureProcessSignDTO = (PDFSignatureProcessSignDTO) o;
    return Objects.equals(this.identityID, pdFSignatureProcessSignDTO.identityID) &&
        Objects.equals(this.processID, pdFSignatureProcessSignDTO.processID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identityID, processID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PDFSignatureProcessSignDTO {\n");
    
    sb.append("    identityID: ").append(toIndentedString(identityID)).append("\n");
    sb.append("    processID: ").append(toIndentedString(processID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
