/*
 * PapSign API
 * The PapSign API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@papsign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PDFSignatureProcessInfoDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * PDFSignatureProcessesAvailableDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-27T15:04:00.483Z[GMT]")
public class PDFSignatureProcessesAvailableDTO {
  @SerializedName("available")
  private List<PDFSignatureProcessInfoDTO> available = new ArrayList<PDFSignatureProcessInfoDTO>();

  public PDFSignatureProcessesAvailableDTO available(List<PDFSignatureProcessInfoDTO> available) {
    this.available = available;
    return this;
  }

  public PDFSignatureProcessesAvailableDTO addAvailableItem(PDFSignatureProcessInfoDTO availableItem) {
    this.available.add(availableItem);
    return this;
  }

   /**
   * Get available
   * @return available
  **/
  @Schema(required = true, description = "")
  public List<PDFSignatureProcessInfoDTO> getAvailable() {
    return available;
  }

  public void setAvailable(List<PDFSignatureProcessInfoDTO> available) {
    this.available = available;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PDFSignatureProcessesAvailableDTO pdFSignatureProcessesAvailableDTO = (PDFSignatureProcessesAvailableDTO) o;
    return Objects.equals(this.available, pdFSignatureProcessesAvailableDTO.available);
  }

  @Override
  public int hashCode() {
    return Objects.hash(available);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PDFSignatureProcessesAvailableDTO {\n");
    
    sb.append("    available: ").append(toIndentedString(available)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
