/*
 * PapSign API
 * The PapSign API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@papsign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * PDFSignatureStatusDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-27T15:04:00.483Z[GMT]")
public class PDFSignatureStatusDTO {
  @SerializedName("dateSigned")
  private OffsetDateTime dateSigned = null;

  @SerializedName("signed")
  private Boolean signed = null;

  public PDFSignatureStatusDTO dateSigned(OffsetDateTime dateSigned) {
    this.dateSigned = dateSigned;
    return this;
  }

   /**
   * Get dateSigned
   * @return dateSigned
  **/
  @Schema(description = "")
  public OffsetDateTime getDateSigned() {
    return dateSigned;
  }

  public void setDateSigned(OffsetDateTime dateSigned) {
    this.dateSigned = dateSigned;
  }

  public PDFSignatureStatusDTO signed(Boolean signed) {
    this.signed = signed;
    return this;
  }

   /**
   * Get signed
   * @return signed
  **/
  @Schema(required = true, description = "")
  public Boolean isSigned() {
    return signed;
  }

  public void setSigned(Boolean signed) {
    this.signed = signed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PDFSignatureStatusDTO pdFSignatureStatusDTO = (PDFSignatureStatusDTO) o;
    return Objects.equals(this.dateSigned, pdFSignatureStatusDTO.dateSigned) &&
        Objects.equals(this.signed, pdFSignatureStatusDTO.signed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateSigned, signed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PDFSignatureStatusDTO {\n");
    
    sb.append("    dateSigned: ").append(toIndentedString(dateSigned)).append("\n");
    sb.append("    signed: ").append(toIndentedString(signed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
